# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [1]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [3]:
#code here

df["Type 1"].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [4]:
df["Type 2"].unique()

array(['Poison', nan, 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)

In [14]:
dragon_hp = df[(df["Type 1"] == "Dragon") | (df["Type 2"] == "Dragon")]["HP"]
grass_hp = df[(df["Type 1"] == "Grass") | (df["Type 2"] == "Grass")]["HP"]

In [16]:
grass_hp

0      45
1      60
2      80
3      80
48     45
       ..
783    59
784    65
785    55
786    75
787    85
Name: HP, Length: 95, dtype: int64

In [17]:
# Run t-tes 

# H0: dragon mean HP <= grass mean HP 
# H1: dragon mean HP > grass mean HP 

st.ttest_ind(dragon_hp, grass_hp, equal_var=False)

TtestResult(statistic=np.float64(4.097528915272702), pvalue=np.float64(0.00010181538122353851), df=np.float64(77.58086781513519))

In [ ]:
# Obtained a p-value of 0.00010181538122353851 which is below 0.05 hence rejecting the null hypothesis. 
# This means that dragon pokemons have higher HP than grass pokemons, and the difference is statistically significant.

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [19]:
df.head()

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [ ]:
# H0:  Legendary and Non-Legendary pokemons have the same stats 
# H1: Legendary and Non-Legendary pokemons have differents stats

In [23]:
legendary = df[df["Legendary"] == True][["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def",  "Speed"]]
non_legendary = df[df["Legendary"] == False][["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def",  "Speed"]]

In [24]:
st.ttest_ind(legendary, non_legendary, equal_var=False)

TtestResult(statistic=array([ 8.98137048, 10.43813354,  7.63707816, 13.41744998, 10.01569661,
       11.47504445]), pvalue=array([1.00269117e-13, 2.52037245e-16, 4.82699849e-11, 1.55146141e-21,
       2.29493279e-15, 1.04901631e-18]), df=array([79.52467831, 75.88324448, 77.71095111, 74.24631138, 73.25892564,
       81.62110996]))

In [31]:
stats = ["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def",  "Speed"]

for stat in stats: 
    legendary = df[df["Legendary"] == True][stat]
    non_legendary = df[df["Legendary"] == False][stat]

    t, p_value = st.ttest_ind(legendary, non_legendary, equal_var=False)

    print(f"p_value of {stat} is: {p_value:}")

    if p_value < 0.05: 
        print ("Reject Ho")
    else: 
        print ("Failed to reject H0")
    print()

p_value of HP is: 1.0026911708035284e-13
Reject Ho

p_value of Attack is: 2.520372449236646e-16
Reject Ho

p_value of Defense is: 4.8269984949193316e-11
Reject Ho

p_value of Sp. Atk is: 1.5514614112239812e-21
Reject Ho

p_value of Sp. Def is: 2.2949327864052826e-15
Reject Ho

p_value of Speed is: 1.049016311882451e-18
Reject Ho

In [ ]:
# All stats shows a p-value below 0.05 hence rejecting the H0. 
# There are significant stats difference between Legendary and non-Legendary pokemons.

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [3]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [ ]:
# group close = -118.34 -0.50 & -122.37 -0.50

In [8]:
import numpy as np

def euclidean_distance(x, y, x0, y0):
    return np.sqrt((x - x0)**2 + (y - y0)**2)

In [9]:
# Calculate distances
df["dist_school"] = euclidean_distance(
    df["longitude"],
    df["latitude"],
    -118,
    34
)

df["dist_hospital"] = euclidean_distance(
    df["longitude"],
    df["latitude"],
    -122,
    37
)

In [10]:
# Close if near either school or hospital
df["close"] = (
    (df["dist_school"] < 0.5) |
    (df["dist_hospital"] < 0.5)
)

In [11]:
# Split groups
close_house = df[df["close"]]["median_house_value"]
far_house = df[~df["close"]]["median_house_value"]

In [14]:
# t-test

# H0: Houses close to a school or hospital are not more expensive.
# H1: H0: Houses close to a school or hospital are significantly more expensive.

from scipy.stats import ttest_ind
t_stat, p_value = ttest_ind(
    close_house,
    far_house,
    equal_var=False
)

print("t statistic:", t_stat)
print("p-value:", p_value)

if p_value < 0.05:
    print("Reject H0: Houses close to a school or hospital are significantly more expensive.")
else:
    print("Fail to reject H0: There is insufficient evidence that nearby houses are more expensive.")

t statistic: 37.992330214201516
p-value: 3.0064957768592614e-301
Reject H0: Houses close to a school or hospital are significantly more expensive.