# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [3]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df.head()

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [3]:
alpha = 0.05 #significance lvl

In [6]:
#code here
dragons_HP  = df[df["Type 2"] == "Dragon"]["HP"]
dragons_HP_mean = dragons_HP.mean()

grass_HP = df[df["Type 1"] == "Grass"]["HP"]
grass_HP_mean = grass_HP.mean()
#standard deviation of sample
# s_HP_mean = dragons_HP_mean.std(ddof=1) # Bessel's correction
n = len(dragons_HP)
#hypothesized population mean
# mu = 65

# dragons_HP_mean, s_HP_mean
# dragons.shape, 
grass_HP.shape

(70,)

In [7]:
critical_value = st.t.ppf(1-alpha,df=n-1)
print(f"The critical value is {critical_value: .2f}")

The critical value is  1.74

In [8]:
statistic, p_value = st.ttest_1samp(dragons_HP, grass_HP_mean, alternative = "greater")
statistic, p_value

(np.float64(2.150931137602062), np.float64(0.023078155161165858))

In [9]:
if p_value > alpha:
    print("We are not able to reject the null hypothesis")
else:
    print("We reject the null hypothesis")

We reject the null hypothesis

H0 is rejected

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [14]:
df_legendary = df[df["Legendary"] == True][["HP","Attack","Defense","Sp. Atk","Sp. Def","Speed"]]
df_non_legendary = df[df["Legendary"] == False][["HP","Attack","Defense","Sp. Atk","Sp. Def","Speed"]]

In [15]:
df.shape[0] == df_legendary.shape[0] + df_non_legendary.shape[0]

True

In [19]:
#code here
alpha = 0.05
statistics, p_values = st.f_oneway(df_legendary, df_non_legendary)
statistics, p_values

(array([ 64.57929545, 108.10428447,  51.5702097 , 201.39601024,
        121.83194849,  95.35980156]),
 array([3.33064768e-15, 7.82725300e-24, 1.58422261e-12, 6.31491577e-41,
        1.84398096e-26, 2.35407544e-21]))

In [20]:
reject = False
for p in p_values:
    if p > alpha:
        reject = True

if reject == True:
    print("We are not able to reject the null hypothesis")
else:
    print("We reject the null hypothesis")

We reject the null hypothesis

Solution

In [ ]:
# Part 1
# Filter all dragon and grass types from both columns
dragons = df[(df["Type 1"] == "Dragon") | (df["Type 2"] == "Dragon")]["HP"]
grass = df[(df["Type 1"] == "Grass") | (df["Type 2"] == "Grass")]["HP"]
# Independent t-test
stat, p = st.ttest_ind(dragons, grass, alternative='greater')

In [ ]:
# Part 2
for stat in ["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]:
    stat_result = st.ttest_ind(df_legendary[stat], df_non_legendary[stat])
    print(stat, stat_result.pvalue)

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [4]:
import function
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [5]:
school_coords = (-118, 34)
hospital_coords = (-122, 37)

# Calculate distances to school and hospital
df['distance_to_school'] = function.euclidean_distance(df['longitude'], df['latitude'], school_coords[0], school_coords[1])
df['distance_to_hospital'] = function.euclidean_distance(df['longitude'], df['latitude'], hospital_coords[0], hospital_coords[1])

In [6]:
df['is_close'] = (df['distance_to_school'] < 0.50) | (df['distance_to_hospital'] < 0.50)

# Separate into close and far groups
close_houses = df[df['is_close']]['median_house_value']
far_houses = df[~df['is_close']]['median_house_value']

In [13]:
# Perform two-sample t-test (one-tailed)
# t_stat, p_value = st.ttest_ind(close_houses, far_houses, equal_var=True)
t_stat, p_value = st.ttest_ind(close_houses, far_houses,equal_var=False,alternative = "two-sided")
t_stat, p_value

(np.float64(37.992330214201516), np.float64(3.0064957768592614e-301))

In [9]:
# p_value_one_tailed = p_value / 2

In [14]:
alpha = 0.05
if p_value < alpha:
    print("Reject H0: Houses close to a school or hospital are significantly more expensive.")
else:
    print("Fail to reject H0")

Reject H0: Houses close to a school or hospital are significantly more expensive.