# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [2]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [5]:
df_dragon = df[df["Type 1"]=="Dragon"]["HP"]
df_grass = df[df["Type 1"]=="Grass"]["HP"]

In [7]:
t_stat, p_value = st.ttest_ind(df_dragon, df_grass, equal_var=False)

In [8]:
alpha = 0.05

if p_value < alpha:
    print("Reject H0")
else:
    print("Fail to reject H0")

Reject H0

At a 5% significance level, a two-sample Welch t-test was conducted to compare the HP of Dragon-type and Grass-type Pokémon.
The results indicate that Dragon-type Pokémon have a significantly higher mean HP than Grass-type Pokémon (t = 3.33, p < 0.05).
Therefore, we reject the null hypothesis.

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [16]:
stats_cols = ["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]

In [17]:
results = []

alpha = 0.05
alpha_bonf = alpha / len(stats_cols) 

for col in stats_cols:
    legendary = df[df["Legendary"]][col]
    non_legendary = df[~df["Legendary"]][col]
    
    t_stat, p_value = st.ttest_ind(
        legendary,
        non_legendary,
        equal_var=False
    )
    
    results.append({
        "Stat": col,
        "Legendary Mean": legendary.mean(),
        "Non-Legendary Mean": non_legendary.mean(),
        "t-statistic": t_stat,
        "p-value": p_value,
        "Significant (Bonferroni)": p_value < alpha_bonf
    })

In [18]:
results_df = pd.DataFrame(results)
results_df

,Stat,Legendary Mean,Non-Legendary Mean,t-statistic,p-value,Significant (Bonferroni)
0,HP,92.738462,67.182313,8.981370,1.002691e-13,True
1,Attack,116.676923,75.669388,10.438134,2.520372e-16,True
2,Defense,99.661538,71.559184,7.637078,4.826998e-11,True
3,Sp. Atk,122.184615,68.454422,13.417450,1.551461e-21,True
4,Sp. Def,105.938462,68.892517,10.015697,2.294933e-15,True
5,Speed,100.184615,65.455782,11.475044,1.049016e-18,True

Six independent Welch t-tests were conducted to compare the base stats of Legendary and Non-Legendary Pokémon.
After applying a Bonferroni correction (α = 0.05/6), significant differences were found across multiple stats, indicating that Legendary Pokémon have overall superior base attributes.

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [20]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [21]:
school = (-118, 34)    
hospital = (-122, 37)

def euclidean_distance(lon, lat, point):
    lon0, lat0 = point
    return np.sqrt((lon - lon0)**2 + (lat - lat0)**2)

df["dist_school"] = euclidean_distance(df["longitude"], df["latitude"], school)
df["dist_hospital"] = euclidean_distance(df["longitude"], df["latitude"], hospital)

df["dist_min"] = df[["dist_school", "dist_hospital"]].min(axis=1)
df[["longitude","latitude","dist_school","dist_hospital","dist_min"]].head()

   longitude  latitude  dist_school  dist_hospital  dist_min
0    -114.31     34.19     3.694888       8.187319  3.694888
1    -114.47     34.40     3.552591       7.966235  3.552591
2    -114.56     33.69     3.453940       8.143077  3.453940
3    -114.57     33.64     3.448840       8.154416  3.448840
4    -114.57     33.57     3.456848       8.183508  3.456848

In [22]:
threshold = 0.50
df["close"] = df["dist_min"] < threshold

df["close"].value_counts()

close
False    10171
True      6829
Name: count, dtype: int64

In [23]:
price_col = "median_house_value"

df_clean = df.dropna(subset=[price_col, "close"]).copy()

close_prices = df_clean.loc[df_clean["close"], price_col]
far_prices   = df_clean.loc[~df_clean["close"], price_col]

len(close_prices), len(far_prices), close_prices.head()

(6829,
 10171,
 2366    124700.0
 2367    137500.0
 2368    169100.0
 2371    182900.0
 2372    220800.0
 Name: median_house_value, dtype: float64)

In [24]:
summary = pd.DataFrame({
    "group": ["close", "far"],
    "n": [len(close_prices), len(far_prices)],
    "mean": [close_prices.mean(), far_prices.mean()],
    "median": [close_prices.median(), far_prices.median()],
    "std": [close_prices.std(ddof=1), far_prices.std(ddof=1)]
})
summary

   group      n           mean    median            std
0  close   6829  246951.982135  218200.0  111823.983975
1    far  10171  180678.441058  149800.0  111019.113084

In [25]:
diff_mean = close_prices.mean() - far_prices.mean()
diff_median = close_prices.median() - far_prices.median()
diff_mean, diff_median

(np.float64(66273.54107710271), 68400.0)

In [26]:
t_stat, p_two = st.ttest_ind(close_prices, far_prices, equal_var=False)


if t_stat > 0:
    p_one = p_two / 2
else:
    p_one = 1 - (p_two / 2)

t_stat, p_two, p_one

(np.float64(37.992330214201516),
 np.float64(3.0064957768592614e-301),
 np.float64(1.5032478884296307e-301))

In [27]:
alpha = 0.05

if p_one < alpha:
    print("Reject H0")
else:
    print("Fail to reject H0")

Reject H0