# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [1]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [14]:
dragon_pokemon = df[df["Type 1"]=="Dragon"]["HP"]
grass_pokemon = df[df["Type 2"]=="Grass"]["HP"]

In [1]:
#Two Sample T-test

#Set the hypothesis:
#H0: mu Dragon_Stats <= Grass_Stats
#H1: mu Grass_Stats > Grass_Stats

#significance level = 0.05

In [15]:
st.ttest_ind(dragon_pokemon, grass_pokemon, equal_var=False)

TtestResult(statistic=np.float64(3.840727789973186), pvalue=np.float64(0.0003219272007036749), df=np.float64(54.507654005585586))

In [ ]:
#Because p_value is lower than significance level, we reject the null hypothesis, 
# this means that Grass pokemons, on average, have more HP stats than grass

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [ ]:
#Two Sample T-test

#Set the hypothesis:
#H0: mu Legendary_Stats = Non_Legndary_Stats
#H1: mu Legendary_Stats != Non_Legndary_Stats

#significance level = 0.05

In [30]:
# "HP" Stat
legendary_pokemon = df[df["Legendary"]==True]["HP"]
non_legendary_pokemon = df[df["Legendary"]==False]["HP"]

st.ttest_ind(legendary_pokemon, non_legendary_pokemon, equal_var=False)

TtestResult(statistic=np.float64(8.981370483625046), pvalue=np.float64(1.0026911708035284e-13), df=np.float64(79.52467830799894))

In [31]:
# "Attack" Stat
legendary_pokemon = df[df["Legendary"]==True]["Attack"]
non_legendary_pokemon = df[df["Legendary"]==False]["Attack"]

st.ttest_ind(legendary_pokemon, non_legendary_pokemon, equal_var=False)

TtestResult(statistic=np.float64(10.438133539322203), pvalue=np.float64(2.520372449236646e-16), df=np.float64(75.88324448141854))

In [32]:
# "Defense" Stat
legendary_pokemon = df[df["Legendary"]==True]["Defense"]
non_legendary_pokemon = df[df["Legendary"]==False]["Defense"]

st.ttest_ind(legendary_pokemon, non_legendary_pokemon, equal_var=False)

TtestResult(statistic=np.float64(7.637078164784618), pvalue=np.float64(4.8269984949193316e-11), df=np.float64(77.7109511135786))

In [34]:
# "Sp. Atk" Stat
legendary_pokemon = df[df["Legendary"]==True]["Sp. Atk"]
non_legendary_pokemon = df[df["Legendary"]==False]["Sp. Atk"]

st.ttest_ind(legendary_pokemon, non_legendary_pokemon, equal_var=False)

TtestResult(statistic=np.float64(13.417449984138461), pvalue=np.float64(1.5514614112239812e-21), df=np.float64(74.24631137998881))

In [35]:
# "Sp. Def" Stat
legendary_pokemon = df[df["Legendary"]==True]["Sp. Def"]
non_legendary_pokemon = df[df["Legendary"]==False]["Sp. Def"]

st.ttest_ind(legendary_pokemon, non_legendary_pokemon, equal_var=False)

TtestResult(statistic=np.float64(10.015696613114878), pvalue=np.float64(2.2949327864052826e-15), df=np.float64(73.2589256447719))

In [36]:
# "Speed" Stat
legendary_pokemon = df[df["Legendary"]==True]["Speed"]
non_legendary_pokemon = df[df["Legendary"]==False]["Speed"]

st.ttest_ind(legendary_pokemon, non_legendary_pokemon, equal_var=False)

TtestResult(statistic=np.float64(11.47504444631443), pvalue=np.float64(1.049016311882451e-18), df=np.float64(81.62110995711882))

In [33]:
# Because p_value is lower than significance level in all stats, we reject the null hypothesis, 
# this means that Legendary pokemons, on average, have a different Defense stats in all categories if compared with Non Legendary ones

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [37]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [ ]:
#Two Sample T-test

# H0: mean(median_house_value | longitude == -118.34) = mean(median_house_value | longitude != -118.34)
# H1: mean(median_house_value | longitude == -118.34) != mean(median_house_value | longitude != -118.34)

#significance level = 0.05

In [42]:
# 1 -- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.

import numpy as np

def euclidean_distance(lon1, lat1, lon2, lat2):
    return np.sqrt((lon1 - lon2)**2 + (lat1 - lat2)**2)

In [48]:
# 2 -- Divide your dataset into houses close and far from either a hospital or school.
lon_school = -118
lat_school = 34

lon_hospital = -122
lat_hospital = 37

df["dist_school"] = euclidean_distance(df["longitude"], df["latitude"],
                                       lon_school, lat_school)

df["dist_hospital"] = euclidean_distance(df["longitude"], df["latitude"],
                                         lon_hospital, lat_hospital)

In [56]:
# 3-- Choose the propper test and, with 5% significance, comment your findings.
near = df[df["dist_school"] <= 1]["median_house_value"]
far  = df[df["dist_school"] > 1]["median_house_value"]

st.ttest_ind(near, far, equal_var=False)

TtestResult(statistic=np.float64(23.54244221315643), pvalue=np.float64(1.8388144266541628e-120), df=np.float64(15660.330268605314))

In [ ]:
# Because p_value is lower than significance level, we reject the null hypothesis, 
# this means that houses close to either a school or a hospital are more expensive