# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [1]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [ ]:
#code here

# HO: HPdragonAVG <= HPgrassAVG 
# H1: HPdragonAVG > HPgrassAVG

In [4]:
df_dragon = df[df["Type 1"] == "Dragon"]['HP']
df_grass = df[df["Type 1"] == "Grass"]['HP']

In [8]:
# 1 tail test   
st.ttest_ind(df_dragon, df_grass, alternative='greater')

TtestResult(statistic=np.float64(3.590444254130357), pvalue=np.float64(0.0002567969150153484), df=np.float64(100.0))

pvalue is much lower than the alpha. This means that the data did not happen by change and that I can reject the null hypotesis

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [10]:
#code here

# HO: AVGstats_legendary == AVGstats_non_legendary
# H1: AVGstats_legendary != AVGstats_non_legendary

stats = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']

# 2 tail test 
for stat in stats:
    legendary = df[df['Legendary'] == True][stat]
    non_legendary = df[df['Legendary'] == False][stat]
    result = st.ttest_ind(legendary, non_legendary)
    print(f"{stat}: {result}")

HP: TtestResult(statistic=np.float64(8.036124405043928), pvalue=np.float64(3.3306476848461905e-15), df=np.float64(798.0))
Attack: TtestResult(statistic=np.float64(10.397321023700622), pvalue=np.float64(7.827253003205253e-24), df=np.float64(798.0))
Defense: TtestResult(statistic=np.float64(7.181240122992339), pvalue=np.float64(1.5842226094427243e-12), df=np.float64(798.0))
Sp. Atk: TtestResult(statistic=np.float64(14.191406210846289), pvalue=np.float64(6.314915770427278e-41), df=np.float64(798.0))
Sp. Def: TtestResult(statistic=np.float64(11.03775106120522), pvalue=np.float64(1.843980958040965e-26), df=np.float64(798.0))
Speed: TtestResult(statistic=np.float64(9.765234331931898), pvalue=np.float64(2.3540754436898388e-21), df=np.float64(798.0))

In [9]:
print(df['Legendary'].dtype)

bool

For all stats the pvalue is way smaller than the alpha, which means we can reject the H0 and say that te stats are indeed different depending on the legendary status of the pokemon

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [11]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [15]:
def distance_from_school(df):
    return np.sqrt((df['longitude'] - (-118))**2 + (df['latitude'] - 34)**2)

def distance_from_hospital(df):
    return np.sqrt((df['longitude'] - (-122))**2 + (df['latitude'] - 37)**2)

In [16]:
df['close_to_school'] = distance_from_school(df) < 0.5
df['close_to_hospital'] = distance_from_hospital(df) < 0.5

In [17]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,close_to_school,close_to_hospital
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,False,False
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,False,False
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,False,False
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,False,False
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,False,False

In [18]:
df_close_to_school = df[df["close_to_school"] == True]
df_close_to_hospital = df[df["close_to_hospital"] == True]

In [23]:
df_close_to_school.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,close_to_school,close_to_hospital
2366,-117.51,34.00,36.0,3791.0,746.0,2258.0,672.0,3.2067,124700.0,True,False
2367,-117.51,33.97,35.0,352.0,62.0,184.0,57.0,3.6691,137500.0,True,False
2368,-117.51,33.95,12.0,9016.0,1486.0,4285.0,1457.0,4.9984,169100.0,True,False
2371,-117.52,33.99,14.0,13562.0,2057.0,7600.0,2086.0,5.2759,182900.0,True,False
2372,-117.52,33.89,2.0,17978.0,3217.0,7305.0,2463.0,5.1695,220800.0,True,False

In [24]:
df_close_to_hospital.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,close_to_school,close_to_hospital
12333,-121.51,37.02,19.0,2372.0,394.0,1142.0,365.0,4.0238,374600.0,False,True
12361,-121.53,36.85,23.0,3359.0,725.0,1862.0,651.0,2.6719,193600.0,False,True
12408,-121.56,37.08,17.0,6725.0,1051.0,3439.0,1027.0,6.4313,393100.0,False,True
12419,-121.57,37.02,17.0,2889.0,624.0,2681.0,608.0,2.9417,178000.0,False,True
12420,-121.57,36.98,14.0,5231.0,817.0,2634.0,799.0,4.9702,279800.0,False,True

In [21]:
df_close = df[df['close_to_school'] | df['close_to_hospital']]
df_far = df[~(df['close_to_school'] | df['close_to_hospital'])]

In [26]:
# Hypotesis test for house value based on proximity to school or hospital
# H0: AVGhouse_value_close <= AVGhouse_value_far
# H1: AVGhouse_value_close > AVGhouse_value_far

st.ttest_ind(df_close['median_house_value'], df_far['median_house_value'], alternative='greater')

TtestResult(statistic=np.float64(38.04632342033554), pvalue=np.float64(2.408917945663479e-304), df=np.float64(16998.0))

With pvalue very below 0,05, we can reject the H0. This means that houses close to schools or hospitals have a higher average price than houses away from these points