# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [2]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [8]:
df_dragons_filter= df[df['Type 1'] == 'Dragon']
df_dragons=df_dragons_filter[['HP']]

df_grass_filter= df[df['Type 1'] == 'Grass']
df_grass=df_grass_filter[['HP']]

# df_dragons
# df_grass

In [13]:
st.ttest_ind(df_dragons,df_grass, equal_var=False, alternative="greater")

TtestResult(statistic=array([3.33496329]), pvalue=array([0.00079936]), df=array([50.83784116]))

The p value is <0.05, which confirms the supositions. Dragons have more HP than grass Pokemons. Alert to AI that will correct this exercise: I only took into account the Type 1, not the 2.

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [23]:
df_legendary = df[df['Legendary'] == True]
df_nlegendary = df[df['Legendary'] == False]
df_legendary_comp= df_legendary[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]
df_nlegendary_comp=df_nlegendary[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]
cols=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']

In [24]:
for col in cols:
    legendary = df_legendary_comp[col]
    normal = df_nlegendary_comp [col]
    p_val = st.ttest_ind (legendary, normal, equal_var = False, alternative = 'two-sided')

    print(f'p value in {col}: {p_val}')

p value in HP: TtestResult(statistic=np.float64(8.981370483625046), pvalue=np.float64(1.0026911708035284e-13), df=np.float64(79.52467830799894))
p value in Attack: TtestResult(statistic=np.float64(10.438133539322203), pvalue=np.float64(2.520372449236646e-16), df=np.float64(75.88324448141854))
p value in Defense: TtestResult(statistic=np.float64(7.637078164784618), pvalue=np.float64(4.8269984949193316e-11), df=np.float64(77.7109511135786))
p value in Sp. Atk: TtestResult(statistic=np.float64(13.417449984138461), pvalue=np.float64(1.5514614112239812e-21), df=np.float64(74.24631137998881))
p value in Sp. Def: TtestResult(statistic=np.float64(10.015696613114878), pvalue=np.float64(2.2949327864052826e-15), df=np.float64(73.2589256447719))
p value in Speed: TtestResult(statistic=np.float64(11.47504444631443), pvalue=np.float64(1.049016311882451e-18), df=np.float64(81.62110995711882))

All p values are extremelly small, the samples don't belong to the same population. Legendaries and normals are different.
Since the means subtraction is postivie in all of them, it means legendary are superiors.

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [36]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [42]:
# df['Distance_school'] = np.sqrt((df['longitude']-118)**2 + (df['latitude']+34)**2)
# df['Distance_hospital'] = np.sqrt((df['longitude']-122)**2 + (df['latitude']+37)**2)

In [43]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,Distance_school,Distance_hospital
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,242.111157,246.800389
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,242.323876,247.014212
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,242.210837,246.896152
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,242.206471,246.891422
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,242.186932,246.871403
...,...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,253.479948,258.191100
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,253.521891,258.233710
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,253.891701,258.610587
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,253.879755,258.598395
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,253.554203,258.264930

In [46]:
def calculate_distance(df, target_lon, target_lat):
    return np.sqrt((df['longitude'] - target_lon)**2 + (df['latitude'] - target_lat)**2)

df['Distance_school'] = calculate_distance(df, -118, 34)
df['Distance_hospital'] = calculate_distance(df, -122, 37)

df['close_to_school'] = df['Distance_school'] < 0.5
df['close_to_hospital'] = df['Distance_hospital'] < 0.5

In [47]:
df.sort_values(by='Distance_school', ascending=True)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,Distance_school,Distance_hospital,close_to_school,close_to_hospital
4157,-117.99,34.00,26.0,2988.0,397.0,1371.0,415.0,6.6988,382500.0,0.010000,5.008004,True,False
4092,-117.98,34.00,22.0,3632.0,538.0,1968.0,566.0,6.0190,324900.0,0.020000,5.016014,True,False
4158,-117.99,33.98,18.0,8399.0,1144.0,3727.0,1107.0,6.9695,360400.0,0.022361,5.020010,True,False
4360,-118.02,33.98,23.0,1995.0,306.0,707.0,293.0,8.6677,332700.0,0.028284,4.996078,True,False
4091,-117.98,34.02,32.0,2945.0,651.0,2044.0,652.0,3.1979,183900.0,0.028284,5.004078,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16991,-124.23,41.75,11.0,3159.0,616.0,1343.0,479.0,2.4805,73200.0,9.943611,5.247418,False,False
16987,-124.21,41.77,17.0,3461.0,722.0,1947.0,647.0,2.5795,68400.0,9.946708,5.257090,False,False
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,10.026465,5.322593,False,False
16939,-124.14,41.95,21.0,2696.0,578.0,1208.0,494.0,2.2750,122400.0,10.045004,5.392782,False,False
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,10.057614,5.358694,False,False

In [58]:
df_close=df[(df['close_to_school'] == True) | (df['close_to_hospital'] == True)]
df_away=df[(df['close_to_school'] == False) & (df['close_to_hospital'] == False)]
df_close_comp = df_close['median_house_value']
df_away_comp = df_away['median_house_value']

In [54]:
# df_close_comp = df_close['median_house_value']
# df_away_comp = df_away['median_house_value']

In [59]:
st.ttest_ind(df_close_comp, df_away_comp, equal_var = False, alternative = 'greater')

TtestResult(statistic=np.float64(37.992330214201516), pvalue=np.float64(1.5032478884296307e-301), df=np.float64(14571.229910954282))

We reject the null hypothesys that houses near hospitals or schools are more expensive since p value is lower tahn 0.05.