# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [1]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [8]:
df[df['Type 2'] == 'Dragon']

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
7,Mega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
196,Mega Ampharos,Electric,Dragon,90,95,105,165,110,45,2,False
249,Kingdra,Water,Dragon,75,95,95,95,95,85,2,False
275,Mega Sceptile,Grass,Dragon,70,110,75,145,85,145,3,False
360,Vibrava,Ground,Dragon,50,70,50,50,50,70,3,False
361,Flygon,Ground,Dragon,80,100,80,80,80,100,3,False
540,Dialga,Steel,Dragon,100,120,120,150,100,90,4,True
541,Palkia,Water,Dragon,90,120,100,150,120,100,4,True
544,Giratina Altered Forme,Ghost,Dragon,150,100,120,100,120,90,4,True
545,Giratina Origin Forme,Ghost,Dragon,150,120,100,120,100,90,4,True
694,Deino,Dark,Dragon,52,65,50,45,50,38,5,False
695,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
696,Hydreigon,Dark,Dragon,92,105,90,125,90,98,5,False
761,Dragalge,Poison,Dragon,65,75,90,97,123,44,6,False
766,Tyrunt,Rock,Dragon,58,89,77,45,45,48,6,False
767,Tyrantrum,Rock,Dragon,82,121,119,69,59,71,6,False
790,Noibat,Flying,Dragon,40,30,35,45,40,55,6,False
791,Noivern,Flying,Dragon,85,70,80,97,80,123,6,False

In [13]:
df.dtypes

Name          object
Type 1        object
Type 2        object
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

In [ ]:
#code here
#H0: HP Polemons Dragon avg =< Grass
#H1: HP Pokemon Dragons avg > Grass

sample_Legendary = df[df['Legendary'] == True]['HP',
sample_nonLegendary = df[df['Legendary'] == False]['HP']
st.ttest_ind(sample_Dragon, sample_Grass, alternative='greater')

#p is smaller than 0.05 so we reject the H0, Hp Pokemon type Dragon is greater than Grass

TtestResult(statistic=np.float64(3.590444254130357), pvalue=np.float64(0.0002567969150153481), df=np.float64(100.0))

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [ ]:
#code here
#H0: stats of Pokemons Non-Legendary = Pokemon Legendary
#H1: stats of Pokemons Non-Legendary != Pokemon Legendary

sample_Dragon = df[df['Type 1'] == 'Dragon'][['HP','Attack','Defense','Sp. Atk',	'Sp. Def','Speed']]
sample_Grass = df[df['Type 1'] == 'Grass'][['HP','Attack','Defense','Sp. Atk',	'Sp. Def','Speed']]
st.ttest_ind(sample_Dragon, sample_Grass)

#all 3 p values are very small, we reject the H0, stats of Pokemon Non Legendary and Legendary are different.

TtestResult(statistic=array([3.59044425, 6.45722714, 2.99532499, 2.7767676 , 3.54014662,
       3.6648417 ]), pvalue=array([5.13593830e-04, 3.88113612e-09, 3.45615702e-03, 6.55577267e-03,
       6.08758212e-04, 3.98264504e-04]), df=array([100., 100., 100., 100., 100., 100.]))

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [17]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [19]:
def add_distances_fast(df):
    school = np.array([-118, 34])
    hospital = np.array([-122, 37])
    
    coords = df[['longitude', 'latitude']].values
    
    df['dist_to_school'] = np.linalg.norm(coords - school, axis=1)
    df['dist_to_hospital'] = np.linalg.norm(coords - hospital, axis=1)
    
    return df

In [20]:
df = add_distances_fast(df)

In [22]:
df['min_distance'] = df[['dist_to_school', 'dist_to_hospital']].min(axis=1)

In [23]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,dist_to_school,dist_to_hospital,min_distance
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,3.694888,8.187319,3.694888
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,3.552591,7.966235,3.552591
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,3.453940,8.143077,3.453940
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,3.448840,8.154416,3.448840
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,3.456848,8.183508,3.456848
...,...,...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,9.082070,4.233675,4.233675
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,9.168915,4.332320,4.332320
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,10.057614,5.358694,5.358694
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,10.026465,5.322593,5.322593
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,9.115597,4.249012,4.249012

In [24]:
def define_close_far(row):
    if row['min_distance'] < 0.5:
        return "close"
    else:
        return "far"
df['close_far'] = df.apply(define_close_far, axis=1)

In [25]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,dist_to_school,dist_to_hospital,min_distance,close_far
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,3.694888,8.187319,3.694888,far
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,3.552591,7.966235,3.552591,far
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,3.453940,8.143077,3.453940,far
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,3.448840,8.154416,3.448840,far
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,3.456848,8.183508,3.456848,far
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,9.082070,4.233675,4.233675,far
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,9.168915,4.332320,4.332320,far
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,10.057614,5.358694,5.358694,far
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,10.026465,5.322593,5.322593,far
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,9.115597,4.249012,4.249012,far

In [ ]:
#H0: Price of House far from school or hospital >= House close from school or hospital
#H1: Price of House far from school or hospital < House close from school or hospital
#p = 0.05
sample_far = df[df['close_far'] == 'far']['median_house_value']
sample_close = df[df['close_far'] == 'close']['median_house_value']

st.ttest_ind(sample_far, sample_close, alternative="less")

#We reject the H0, house close to school or hospital are more expensive

TtestResult(statistic=np.float64(-38.04632342033554), pvalue=np.float64(2.408917945663922e-304), df=np.float64(16998.0))