# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [1]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [34]:
df.describe

<bound method NDFrame.describe of                Name   Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0         Bulbasaur    Grass  Poison  45      49       49       65       65
1           Ivysaur    Grass  Poison  60      62       63       80       80
2          Venusaur    Grass  Poison  80      82       83      100      100
3     Mega Venusaur    Grass  Poison  80     100      123      122      120
4        Charmander     Fire     NaN  39      52       43       60       50
..              ...      ...     ...  ..     ...      ...      ...      ...
795         Diancie     Rock   Fairy  50     100      150      100      150
796    Mega Diancie     Rock   Fairy  50     160      110      160      110
797  Hoopa Confined  Psychic   Ghost  80     110       60      150      130
798   Hoopa Unbound  Psychic    Dark  80     160       60      170      130
799       Volcanion     Fire   Water  80     110      120      130       90

     Speed  Generation  Legendary
0       45           1      False
1       60           1      False
2       80           1      False
3       80           1      False
4       65           1      False
..     ...         ...        ...
795     50           6       True
796    110           6       True
797     70           6       True
798     80           6       True
799     70           6       True

[800 rows x 11 columns]>

In [ ]:
# H0: mu dragon hp <= mu grass hp 
# H1: mu dragon hp > mu grass hp

#sl = 0.05

dragon_hp = df[df["Type 1"] == "Dragon"]["HP"]
grass_hp = df[df["Type 1"] == "Grass"]["HP"]

p_value =  st.ttest_ind(dragon_hp, grass_hp, alternative="greater")

print("P-value:", p_value[1])

#H0 is rejected as p-value is less than 0.05, it shows that Dragon-type Pokémon have higher average HP than Grass-type Pokémon.

P-value: 0.0002567969150153481

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [ ]:
#H0: Mean HP (Legendary) = Mean HP (Non-Legendary)
#H1: Means are different

stats_cols = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']

for col in stats_cols:
    legendary = df[df["Legendary"] == True][col]
    non_legendary = df[df["Legendary"] == False][col]
    
    f_stat, p_value = st.f_oneway(legendary, non_legendary)
    
    print(f"{col}")
    print("F-statistic:", f_stat)
    print("P-value:", p_value)
    print("------------------")

HP
F-statistic: 64.57929545334261
P-value: 3.330647684845447e-15
------------------
Attack
F-statistic: 108.10428446988695
P-value: 7.827253003204001e-24
------------------
Defense
F-statistic: 51.57020970407507
P-value: 1.584222609442392e-12
------------------
Sp. Atk
F-statistic: 201.3960102412466
P-value: 6.314915770426125e-41
------------------
Sp. Def
F-statistic: 121.83194848913693
P-value: 1.8439809580406472e-26
------------------
Speed
F-statistic: 95.35980155754145
P-value: 2.354075443689382e-21
------------------

In [ ]:
#Since p < 0.05 for all, There is strong statistical evidence that Legendary and Non-Legendary Pokémon differ in all six stats.

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [42]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [51]:
"""
mu_close = mean price of houses close to school or hospital
mu_far = mean price of houses far from both

We posit that close houses are more expensive.

H0 = mu_close <= mu_far

h1 = mu_close > mu_far

sl = 0.05
"""

'\nmu_close = mean price of houses close to school or hospital\nmu_far = mean price of houses far from both\n\nWe posit that close houses are more expensive.\n\nH0 = mu_close <= mu_far\n\nh1 = mu_close > mu_far\n\nsl = 0.05\n'

In [44]:


def euclidean_distance(x1, y1, x2, y2):
    return np.sqrt((x1 - x2)**2 + (y1 - y2)**2)

In [46]:
df["dist_school"] = euclidean_distance(df["longitude"], df["latitude"], -118, 34)
df["dist_hospital"] = euclidean_distance(df["longitude"], df["latitude"], -122, 37)

In [47]:
df["close"] = (df["dist_school"] < 0.50) | (df["dist_hospital"] < 0.50)

In [49]:
close_prices = df[df["close"] == True]["median_house_value"]
far_prices = df[df["close"] == False]["median_house_value"]

In [50]:
t_stat, p_value = st.ttest_ind(close_prices, 
                               far_prices, 
                               equal_var=False,
                               alternative="greater")

print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: 37.992330214201516
P-value: 1.5032478884296307e-301

In [ ]:
#H0 is rejected as P-value is less than 0.05
#There is extremely strong statistical evidence that houses located within 0.50 distance units of a school or hospital are more expensive on average.