# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [1]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

### Formulacion hipotesis
- H0 = vida media pokemon dragon = vida media pokemon planta
- H1 = vida media pokemon dragon != vida media pokemon planta

In [14]:
# Extraccion muestras
pokemon_dragon = df[df['Type 1'] == 'Dragon']['HP']
pokemon_planta = df[df['Type 1'] == 'Grass']['HP']

### Elección nivel de significancia (alpha): 0.05

In [21]:
stat, p_value = st.ttest_ind(pokemon_dragon, pokemon_planta, equal_var=False, alternative='greater')

print("P-value:", p_value)

P-value: 0.0007993609745420599

### Conclusion
- Rechazamos la hipotesis nula = H0
- Tenemos evidencias para afirmar que la media de HP de los Pokemon tipo dragon es mayor que las de los Pokemon tipo planta

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

### Formulacion hipotesis
- H0 = estadisticas de  pokemon legendarios  = estadisticas de pokemon no lengendarios 
- H0 = estadisticas de  pokemon legendarios  != estadisticas de pokemon no lengendarios

In [ ]:
# Separamos en dos data sets, Lengendary y No-legendary
legendary = df[df['Legendary']== True]
no_legendary = df[df['Legendary']== False]

# Test para HP
stat_hp = 'HP'
data_legendary = legendary[stat_hp]
data_no_legendary = no_legendary[stat_hp]

stat, p_value = st.ttest_ind(data_legendary, data_no_legendary, equal_var=False)
print(f"Estadística: {stat_hp}")
print(f"P-value: {p_value}")

if p_value < 0.05:
    print("Rechazamos H0: Hay diferencias en HP.")
else:
    print("No rechazamos H0: No hay diferencias en HP.")

Estadística: HP
P-value: 1.0026911708035284e-13
Rechazamos H0: Hay diferencias en HP.

In [ ]:
# Test para Attack
stat_attack = 'Attack'
data_legendary = legendary[stat_attack]
data_no_legendary = no_legendary[stat_attack]

stat, p_value = st.ttest_ind(data_legendary, data_no_legendary, equal_var=False)
print(f"Estadística: {stat_attack}")
print(f"P-value: {p_value}")

if p_value < 0.05:
    print("Rechazamos H0: Hay diferencias en Attack.")
else:
    print("No rechazamos H0: No hay diferencias en Attack.")

Estadística: Attack
P-value: 2.520372449236646e-16
Rechazamos H0: Hay diferencias en HP.

In [47]:
# Test para Defense
stat_defense = 'Defense'
data_legendary = legendary[stat_defense]
data_no_legendary = no_legendary[stat_defense]

stat, p_value = st.ttest_ind(data_legendary, data_no_legendary, equal_var=False)
print(f"Estadística: {stat_defense}")
print(f"P-value: {p_value}")

if p_value < 0.05:
    print("Rechazamos H0: Hay diferencias en Defense.")
else:
    print("No rechazamos H0: No hay diferencias en Defense.")

Estadística: Defense
P-value: 4.8269984949193316e-11
Rechazamos H0: Hay diferencias en Defense.

In [48]:
# Test para Sp. Atk
stat_Sp_Atk = 'Sp. Atk'
data_legendary = legendary[stat_Sp_Atk]
data_no_legendary = no_legendary[stat_Sp_Atk]

stat, p_value = st.ttest_ind(data_legendary, data_no_legendary, equal_var=False)
print(f"Estadística: {stat_Sp_Atk}")
print(f"P-value: {p_value}")

if p_value < 0.05:
    print("Rechazamos H0: Hay diferencias en Sp. Atk.")
else:
    print("No rechazamos H0: No hay diferencias en Sp. Atk.")

Estadística: Sp. Atk
P-value: 1.5514614112239812e-21
Rechazamos H0: Hay diferencias en Sp. Atk.

In [49]:
# Test para Sp. Def
stat_Sp_Def = 'Sp. Def'
data_legendary = legendary[stat_Sp_Def]
data_no_legendary = no_legendary[stat_Sp_Def]

stat, p_value = st.ttest_ind(data_legendary, data_no_legendary, equal_var=False)
print(f"Estadística: {stat_Sp_Def}")
print(f"P-value: {p_value}")

if p_value < 0.05:
    print("Rechazamos H0: Hay diferencias en Sp. Def.")
else:
    print("No rechazamos H0: No hay diferencias en Sp. Def.")

Estadística: Sp. Def
P-value: 2.2949327864052826e-15
Rechazamos H0: Hay diferencias en Sp. Def.

In [50]:
# Test para Speed
stat_Speed = 'Speed'
data_legendary = legendary[stat_Speed]
data_no_legendary = no_legendary[stat_Speed]

stat, p_value = st.ttest_ind(data_legendary, data_no_legendary, equal_var=False)
print(f"Estadística: {stat_Speed}")
print(f"P-value: {p_value}")

if p_value < 0.05:
    print("Rechazamos H0: Hay diferencias en Speed.")
else:
    print("No rechazamos H0: No hay diferencias en Speed.")

Estadística: Speed
P-value: 1.049016311882451e-18
Rechazamos H0: Hay diferencias en Speed.

#### Conclusion
- Rechazamos todas las hipotesis nula = H0
- Tenemos evidencias para afirmar que la media de Stats en pokemon legendarios no son iguales a las Stats medias de pokemon no legendarios. Podemos intuir que los pokemon legendarios son mas fuertes que los no legendarios

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [63]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [66]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

### Hipotesis school
- H0 = Precio medio cercano  = precio medio lejano
- H0 = precio medio cercano != precio medio lejano

#

In [67]:
# Funcion euclidiana
def distacia_euclidiana(lat1, lon1, lat2, lon2):
    return np.sqrt((lat1 - lat2)**2 + (lon1 - lon2)**2)

In [68]:
# Coordenadas

coordenadas_school = [34, -118]
coordenadas_hospital = [37, -122]

In [86]:
# Aplicamos la funcion para obtener las distancias
df['distancia_school'] = distacia_euclidiana(df['latitude'],df['longitude'],coordenadas_school[0],coordenadas_school[1])
df['distancia_hospital'] = distacia_euclidiana(df['latitude'],df['longitude'],coordenadas_hospital[0],coordenadas_hospital[1])
print(df['distancia_school'])
print(df['distancia_hospital'])

0         3.694888
1         3.552591
2         3.453940
3         3.448840
4         3.456848
           ...
16995     9.082070
16996     9.168915
16997    10.057614
16998    10.026465
16999     9.115597
Name: distancia_school, Length: 17000, dtype: float64
0        8.187319
1        7.966235
2        8.143077
3        8.154416
4        8.183508
           ...
16995    4.233675
16996    4.332320
16997    5.358694
16998    5.322593
16999    4.249012
Name: distancia_hospital, Length: 17000, dtype: float64

In [87]:
# Test School

school_cerca = df[df['distancia_school'] < 0.5] ['median_house_value']
school_lejos = df[df['distancia_school'] >= 0.5] ['median_house_value']

stat_s, p_value_s = st.ttest_ind(school_cerca, school_lejos, equal_var=False, alternative='greater')

print(f"P_value School: {p_value_s}")
if p_value_s < 0.05:
    print("Rechazamos H0: Las casas cerca de la escuela son más caras.")
else:
    print("No rechazamos H0: No hay evidencia suficiente.")

P_value School: 3.971237102319547e-129
Rechazamos H0: Las casas cerca de la escuela son más caras.

In [91]:
# Test Hospital

hospital_cerca = df[df['distancia_hospital'] < 0.5] ['median_house_value']
hospital_lejos = df[df['distancia_hospital'] >= 0.5] ['median_house_value']

stat_h, p_value_h = st.ttest_ind(hospital_cerca, hospital_lejos, equal_var=False, alternative='greater')

print(f"P_value Hospital: {p_value_h}")
if p_value_h < 0.05:
    print("Rechazamos H0: Las casas cerca del hospital son más caras.")
else:
    print("No rechazamos H0: No hay evidencia suficiente.")

P_value Hospital: 1.4726146999391155e-143
Rechazamos H0: Las casas cerca del hospital son más caras.

### Conclusion School
- Rechazamos la hipotesis nula = H0
- Tenemos evidencia estadística  para afirmar que el precio medio de las casas que están cerca de una escuela es significativamente mayor que el de las que están lejos.


### Conclusion Hospital
- Rechazamos la hipotesis nula = H0
- Tenemos evidencia estadística  para afirmar que el precio medio de las casas que están cerca de un hospital es significativamente mayor que el de las que están lejos.