# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [2]:
pip install scipy

Collecting scipy
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: numpy<2.7,>=1.26.4 in c:\Users\pilir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scipy) (2.4.4)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.3 MB ? eta -:--:--
    --------------------------------------- 0.5/37.3 MB 1.8 MB/s eta 0:00:21
   - -------------------------------------- 1.0/37.3 MB 2.0 MB/s eta 0:00:19
   - -------------------------------------- 1.6/37.3 MB 2.2 MB/s eta 0:00:17
   -- ------------------------------------- 2.4/37.3 MB 2.4 MB/s eta 0:00:15
   --- ------------------------------------ 3.1/37.3 MB 2.6 MB/s eta 0:00:14
   ---- ----------------------------------- 3.9/37.3 MB 2.8 MB/s eta 0:00:12
   ----- ---------------------------------- 4.7/37.3 MB 3.0 MB/s eta 0:00:12
   ------ --------------------------------- 5.8/37.3 MB 3.2 MB/s eta 0:00:10
   ------- -------------------------------- 6.8/37.3 MB 3.4 MB/s eta 0:00:09
   -------- ------------------------------- 7.9/37.3 MB 3.6 MB/s eta 0:00:09
   --------- ------------------------------ 9.2/37.3 MB 3.8 MB/s eta 0:00:08
   ----------- ---------------------------- 10.5/37.3 MB 4.1 MB/s eta 0:00:07
   ------------ --------------------------- 12.1/37.3 MB 4.3 MB/s eta 0:00:06
   -------------- ------------------------- 13.6/37.3 MB 4.5 MB/s eta 0:00:06
   ---------------- ----------------------- 15.2/37.3 MB 4.7 MB/s eta 0:00:05
   ----------------- ---------------------- 16.8/37.3 MB 4.9 MB/s eta 0:00:05
   ------------------- -------------------- 18.6/37.3 MB 5.1 MB/s eta 0:00:04
   --------------------- ------------------ 20.4/37.3 MB 5.3 MB/s eta 0:00:04
   ----------------------- ---------------- 22.3/37.3 MB 5.5 MB/s eta 0:00:03
   -------------------------- ------------- 24.4/37.3 MB 5.7 MB/s eta 0:00:03
   ---------------------------- ----------- 26.2/37.3 MB 5.9 MB/s eta 0:00:02
   ------------------------------ --------- 28.3/37.3 MB 6.1 MB/s eta 0:00:02
   -------------------------------- ------- 30.7/37.3 MB 6.3 MB/s eta 0:00:02
   ----------------------------------- ---- 33.0/37.3 MB 6.5 MB/s eta 0:00:01
   ------------------------------------- -- 35.1/37.3 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 6.7 MB/s  0:00:05
Installing collected packages: scipy
Successfully installed scipy-1.17.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [12]:
dragon_hp = df[df["Type 1"] == "Dragon"]["HP"]
dragon_hp.mean()

np.float64(83.3125)

In [13]:
grass_hp = df[df["Type 1"] == "Grass"]["HP"]
grass_hp.mean()

np.float64(67.27142857142857)

In [ ]:
#H0: Average of HP Dragon  ≤ Average of HP Grass
#H1: Average of HP Dragon > Average of HP Grass
α = 0.05

In [15]:
result = st.ttest_ind(dragon_hp, grass_hp)

result

TtestResult(statistic=np.float64(3.590444254130357), pvalue=np.float64(0.0005135938300306967), df=np.float64(100.0))

In [ ]:
#pvalue es inferior al significance level, entonces rechazamos la hipotesis nula. Por lo tanto, la media del HP del tipo dragon es superior a la media del tipo Grass.

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [ ]:
#H0: No diferencia entre legendary and non-legendary Pokemon stats. 
#H1: Diferencia entre legendary and non-legendary Pokemon stats. 
α = 0.05

In [16]:
df["total_stats"] = df["HP"] + df["Attack"] + df["Defense"] + df["Sp. Atk"] + df["Sp. Def"] + df["Speed"]

legendary_stats = df[df["Legendary"] == True]["total_stats"]
non_legendary_stats = df[df["Legendary"] == False]["total_stats"]

In [17]:
result = st.ttest_ind(legendary_stats, non_legendary_stats)

result

TtestResult(statistic=np.float64(16.386116965872425), pvalue=np.float64(3.0952457469651812e-52), df=np.float64(798.0))

In [ ]:
#pvalue es mayor que significance level, por lo que rechazamos la hipotesis nula y el resultado seria que si vemos diferencia entre legendary y non-legendary Pokemon en terminos de estadisticas.

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [18]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [ ]:
#H0: Casas cercanas a colegio u hospital no son mas caras que las casas mas lejanas.
#H1: Casas cercanas a colegio u hospital son mas caras que las casas mas lejanas. 
α = 0.05

In [21]:
#Vamos a calcular la distancia que hay entre las casas y el colegio. Vamos a utilizar una funcion de geometria (Funcion: d = √((x₂ - x₁)² + (y₂ - y₁)²))
#x: longitud
#y: latitud

df["distance_to_school"] = np.sqrt((df["longitude"] - (-118))**2 + (df["latitude"] - 34)**2)
df["distance_to_school"]

0         3.694888
1         3.552591
2         3.453940
3         3.448840
4         3.456848
           ...
16995     9.082070
16996     9.168915
16997    10.057614
16998    10.026465
16999     9.115597
Name: distance_to_school, Length: 17000, dtype: float64

In [22]:
#Vamos a calcular la distancia que hay entre las casas y el hospital. 
df["distance_to_hospital"] = np.sqrt((df["longitude"] - (-122))**2 + (df["latitude"] - 37)**2)
df["distance_to_hospital"]

0        8.187319
1        7.966235
2        8.143077
3        8.154416
4        8.183508
           ...
16995    4.233675
16996    4.332320
16997    5.358694
16998    5.322593
16999    4.249012
Name: distance_to_hospital, Length: 17000, dtype: float64

In [24]:
#Vamos a crear una columna donde veamos si las casas estan cercanas a hospital o colegio. 
df["close"] = (df["distance_to_school"] < 0.5) | (df["distance_to_hospital"] < 0.50)
df["close"]

0        False
1        False
2        False
3        False
4        False
         ...
16995    False
16996    False
16997    False
16998    False
16999    False
Name: close, Length: 17000, dtype: bool

In [25]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,distance_to_school,distance_to_hospital,close
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,3.694888,8.187319,False
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,3.552591,7.966235,False
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,3.453940,8.143077,False
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,3.448840,8.154416,False
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,3.456848,8.183508,False

In [26]:
df["close"].value_counts()

close
False    10171
True      6829
Name: count, dtype: int64

In [ ]:
#Vamos a conectar distancia y precios de las casas. 
#Precios de casas lejanas a hospital o colegio.
far_prices = df[df["close"] == False]["median_house_value"]
far_prices

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 10171, dtype: float64

In [ ]:
#Precios de casas cercanas a colegio u hospital
close_prices = df[df["close"] == True]["median_house_value"]
close_prices

2366     124700.0
2367     137500.0
2368     169100.0
2371     182900.0
2372     220800.0
           ...
15090    177500.0
15170    500001.0
15253    277700.0
15254    319400.0
15686    286100.0
Name: median_house_value, Length: 6829, dtype: float64

In [33]:
mean_close_prices = close_prices.mean()
mean_far_prices = far_prices.mean()

mean_close_prices, mean_far_prices

(np.float64(246951.98213501245), np.float64(180678.44105790975))

In [34]:
result = st.ttest_ind(close_prices, far_prices)

result

TtestResult(statistic=np.float64(38.04632342033554), pvalue=np.float64(4.817835891326958e-304), df=np.float64(16998.0))

In [ ]:
#pvalue es inferior al nivel de significancia, por lo que rechazamos la hipotesis nula. Lo cual significa que las casas mas cercanas a hospitales y/o colegios son mas caras que aquellas mas lejanas.