# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [2]:
#librerias
import pandas as pd
import scipy.stats as st
import numpy as np

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [4]:
from scipy.stats import ttest_ind

In [5]:
#filto solo pokemon de tipo Dragon y Grass
dragon_hp = df[df['Type 1'] == 'Dragon']['HP']
grass_hp = df[df['Type 1'] == 'Grass']['HP']

In [6]:
# H0: media HP dragon menor o igual media HP grass
# H1: media HP dragon > media HP grass

#p-value < 0.05, rechazamos H0
#p-value ≥ 0.05, no rechazamos H0

In [7]:
# Prueba T de dos muestras independientes
stat, p_value = ttest_ind(dragon_hp, grass_hp, alternative='greater')

In [8]:
stat

np.float64(3.590444254130357)

In [9]:
p_value

np.float64(0.0002567969150153481)

In [10]:
#como p_value = 0.0003 < 0.05, rechazamos H0
#por lo tanto Los Pokémon de tipo Dragon tienen una media de HP mayor que los de tipo Grass

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [11]:
#separo los dos grupos
legend = df[df['Legendary'] == True]
non_legend = df[df['Legendary'] == False]

### HP

In [14]:
# H0: Pokemon legendarios media HP = no legendarios media de HP
# H1: Tienen medias diferentes de HP

#p-value < 0.05, rechazamos H0
#p-value ≥ 0.05, no rechazamos H0

In [15]:
# Prueba T de dos muestras independientes
stat, p_value = ttest_ind(legend['HP'], non_legend['HP'])
stat, p_value

(np.float64(8.036124405043928), np.float64(3.3306476848461913e-15))

### como p_value = 0.0000....3 < 0.05, rechazamos H0
### por lo tanto Los Pokémon legendarios tienen una media de HP distinta que los no legendarios

### Attack

In [16]:
# H0: Pokemon legendarios media Attack = no legendarios media de Attack
# H1: Tienen medias diferentes de Attack

#p-value < 0.05, rechazamos H0
#p-value ≥ 0.05, no rechazamos H0

In [17]:
# Prueba T de dos muestras independientes
stat, p_value = ttest_ind(legend['Attack'], non_legend['Attack'])
stat, p_value

(np.float64(10.397321023700622), np.float64(7.827253003205333e-24))

In [18]:
#como p_value = 0.0000....7 < 0.05, rechazamos H0
#por lo tanto Los Pokémon legendarios tienen una media de Attack distinta que los no legendarios

### Defense

In [19]:
# H0: Pokemon legendarios media Defense = no legendarios media de Defense
# H1: Tienen medias diferentes de Defense

#p-value < 0.05, rechazamos H0
#p-value ≥ 0.05, no rechazamos H0

In [20]:
# Prueba T de dos muestras independientes
stat, p_value = ttest_ind(legend['Defense'], non_legend['Defense'])
stat, p_value

(np.float64(7.181240122992339), np.float64(1.5842226094427259e-12))

In [21]:
#como p_value = 0.0000....1 < 0.05, rechazamos H0
#por lo tanto Los Pokémon legendarios tienen una media de Defense distinta que los no legendarios

### Sp. Atk

In [22]:
# H0: Pokemon legendarios media Sp. Atk = no legendarios media de Sp. Atk
# H1: Tienen medias diferentes de Sp. Atk

#p-value < 0.05, rechazamos H0
#p-value ≥ 0.05, no rechazamos H0

In [23]:
# Prueba T de dos muestras independientes
stat, p_value = ttest_ind(legend['Sp. Atk'], non_legend['Sp. Atk'])
stat, p_value

(np.float64(14.191406210846289), np.float64(6.314915770427265e-41))

In [24]:
#como p_value = 0.0000....6 < 0.05, rechazamos H0
#por lo tanto Los Pokémon legendarios tienen una media de Sp. Atk distinta que los no legendarios

### Sp. Def

In [25]:
# H0: Pokemon legendarios media Sp. Def = no legendarios media de Sp. Def
# H1: Tienen medias diferentes de Sp. Def

#p-value < 0.05, rechazamos H0
#p-value ≥ 0.05, no rechazamos H0

In [26]:
# Prueba T de dos muestras independientes
stat, p_value = ttest_ind(legend['Sp. Def'], non_legend['Sp. Def'])
stat, p_value

(np.float64(11.03775106120522), np.float64(1.8439809580409597e-26))

In [27]:
#como p_value = 0.0000....1 < 0.05, rechazamos H0
#por lo tanto Los Pokémon legendarios tienen una media de Sp. Def distinta que los no legendarios

### Speed

In [28]:
# H0: Pokemon legendarios media Speed = no legendarios media de Speed
# H1: Tienen medias diferentes de Speed

#p-value < 0.05, rechazamos H0
#p-value ≥ 0.05, no rechazamos H0

In [29]:
# Prueba T de dos muestras independientes
stat, p_value = ttest_ind(legend['Speed'], non_legend['Speed'])
stat, p_value

(np.float64(9.765234331931898), np.float64(2.3540754436898437e-21))

In [30]:
#como p_value = 0.0000....2 < 0.05, rechazamos H0
#por lo tanto Los Pokémon legendarios tienen una media de Speed distinta que los no legendarios

### con bucle

In [12]:
#estadisticas a comparar
stats = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']

In [41]:
for stat in stats:
    stat_test, p_value = ttest_ind(legend[stat], non_legend[stat], equal_var=False)
    print(f'{stat} - t-statistic: {stat_test}, p-value: {p_value}')

HP - t-statistic: 8.981370483625046, p-value: 1.0026911708035284e-13
Attack - t-statistic: 10.438133539322203, p-value: 2.520372449236646e-16
Defense - t-statistic: 7.637078164784618, p-value: 4.826998494919331e-11
Sp. Atk - t-statistic: 13.417449984138461, p-value: 1.5514614112239816e-21
Sp. Def - t-statistic: 10.015696613114878, p-value: 2.2949327864052826e-15
Speed - t-statistic: 11.47504444631443, p-value: 1.0490163118824507e-18

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [31]:
import pandas as pd
import numpy as np

In [32]:
df1 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df1.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:

- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.

In [33]:
#buscando en internet la formula seria;
# eucl_dist= raiz cuadrada (x2-x1)**2 + (y2-y1)**2

In [34]:
def euclidean_distance(latitud1, longitud1, latitud2, longitud2):
    return np.sqrt((latitud1 - latitud2)**2 + (longitud1 - longitud2)**2)

In [35]:
school_latitude = 34
school_longitude = -118
hospital_latitude = 37
hospital_longitude = -122

df1['distance_school'] = euclidean_distance(df1['latitude'], df1['longitude'], school_latitude, school_longitude)
df1['distance_hospital'] = euclidean_distance(df1['latitude'], df1['longitude'], hospital_latitude, hospital_longitude)

- Divide your dataset into houses close and far from either a hospital or school.

In [36]:
df1['is_close'] = (df1['distance_school'] < 0.50) | (df1['distance_hospital'] < 0.50)

- Choose the propper test and, with 5% significance, comment your findings.

In [37]:
# 2 grupos
close_prices = df1[df1['is_close'] == True]['median_house_value']
far_prices = df1[df1['is_close'] == False]['median_house_value']

In [ ]:
# H0: casas cercanas a escuela u hospital igual o menor precio que las lejanas
# H1: casas cercanas tienen precio mayor a las lejanas

#p-value < 0.05, rechazamos H0
#p-value ≥ 0.05, no rechazamos H0

In [39]:
# Prueba T de dos muestras independientes
stat, p_value = ttest_ind(close_prices, far_prices, alternative='two-sided')
stat, p_value

(np.float64(38.04632342033554), np.float64(4.817835891327844e-304))

### como p_value = 0.0000....4 < 0.05, rechazamos H0
### por lo tanto las casas cercanas al colegio y hospital tienen una media de precios mayores a las lejanas