# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [14]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [28]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df.columns

Index(['Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [29]:
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [16]:
#Test tipo: Two Sample T-Test (independiente). 
#H0: mu_dragon = mu_grass (No hay diferencia entre Dragon y Grass).
#H1: mu_dragon != mu_grass (Hay diferencia entre Dragon y Grass).

In [17]:
import pandas as pd
import scipy.stats as st

df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")

dragon_pkm = df[df["Type 1"] == "Dragon"]["HP"]
grass_pkm = df[df["Type 1"] == "Grass"]["HP"]

t_stat, p_value = st.ttest_ind(dragon_pkm, grass_pkm, equal_var=False)

In [18]:
p_value_one_tailed = p_value / 2

t_stat, p_value_one_tailed

(np.float64(3.3349632905124063), np.float64(0.0007993609745420597))

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [19]:
#Comparación de distintas categorías de una misma variable (Legendary). 

#Legendary == "Legendary" True
#Non-Legendary == "Legendary" False

#H0: mu_legendary = mu_non_legendary (No hay diferencia entre Legendary y Non-Legendary).
#H1: mu_legendary != mu_non_legendary (Hay diferencia entre Legendary y Non-Legendary).


#Se toman en cuenta los siguientes estadísticos para el análisis:  HP, Attack, Defense, Sp. Atk, Sp. Def, Speed

In [20]:
stats = ["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]

legendary = df[df["Legendary"] == True]
non_legendary = df[df["Legendary"] == False]

for stat in stats:
    t_stat, p_value = st.ttest_ind(
        legendary[stat],
        non_legendary[stat],
        equal_var=False
    )
    
    print(f"{stat} -> p-value = {p_value}")

HP -> p-value = 1.0026911708035284e-13
Attack -> p-value = 2.5203724492366553e-16
Defense -> p-value = 4.8269984949193316e-11
Sp. Atk -> p-value = 1.5514614112239705e-21
Sp. Def -> p-value = 2.294932786405291e-15
Speed -> p-value = 1.0490163118824585e-18

In [21]:
#Notamos que, para todos los estadísticos, p-value < 0.05, por lo que se rechaza la hipótesis nula, y se concluye que hay diferencias significativas entre Pokémon Legendarios y No Legendarios en cuanto a sus estadísticas, con un nivel de confianza del 95%.

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [22]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [23]:
#En primer lugar, a efectos del análisis, tomaremos en cuenta la variable close, la cual crearemos para determinar la ubicación de las viviendas y determinar su cercanía a algún centro educativo o sanitario, para poder determinar si el precio de la misma es elevado o no, y si esto se debe a su cercanía a dichos centros.

#close = True (Cercanía a centros educativos o sanitarios).
#close = False (No cercanía a centros educativos o sanitarios).

#Queremos comparar median_house_value. 

#Tipo de análisis: Two Sample T-Test independiente.

In [24]:
#H0: mu_close = mu_not_close (No hay diferencia en el precio de las viviendas, según su cercanía a centros educativos o sanitarios).
#H1: mu_close != mu_not_close (Hay diferencia en el precio de las viviendas, según su cercanía a centros educativos o sanitarios).

In [25]:
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")

school = (-118, 34)
hospital = (-122, 37)

def distance(lon, lat, point):
    return np.sqrt((lon - point[0])**2 + (lat - point[1])**2)

df["dist_school"] = df.apply(lambda row: distance(row["longitude"], row["latitude"], school), axis=1)
df["dist_hospital"] = df.apply(lambda row: distance(row["longitude"], row["latitude"], hospital), axis=1)

df["close"] = ((df["dist_school"] < 0.5) | (df["dist_hospital"] < 0.5))

In [26]:
close_prices = df[df["close"] == True]["median_house_value"]
far_prices = df[df["close"] == False]["median_house_value"]

t_stat, p_value = st.ttest_ind(close_prices, far_prices, equal_var=False)

p_value_one_tailed = p_value / 2

t_stat, p_value_one_tailed

(np.float64(37.992330214201516), np.float64(1.5032478884296307e-301))

In [27]:
#Luego del respectivo análisis, y con un nivel de confianza del 95%, podemos concluir que hay una diferencia significativa en el precio de las viviendas, según su cercanía a centros educativos o sanitarios, ya que el p-value es menor a 0.05. Esto sugiere que las viviendas cercanas a estos centros tienden a tener un precio diferente (en este caso, probablemente más alto) en comparación con las viviendas que no están cerca de dichos centros.