In [51]:
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")

df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [5]:
df["Type 1"].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [6]:
df["Type 2"].unique()

array(['Poison', nan, 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)

In [ ]:
# H0 = Average HP Dragon <= Average HP Grass
# H1 = Average HP Dragon > Average HP Grass

In [12]:
alpha = 0.05

In [13]:
dragon_hp = df[(df['Type 1'] == 'Dragon') | (df['Type 2'] == 'Dragon')]['HP']
grass_hp = df[(df['Type 1'] == 'Grass') | (df['Type 2'] == 'Grass')]['HP']

In [14]:
_, p_value = st.ttest_ind(dragon_hp, grass_hp, alternative='greater'
                          , equal_var=False)

print(p_value)

5.0907690611769255e-05

In [15]:
if p_value < alpha:
    print("Conclusion: Reject H0. There is statistically significant evidence that Dragon-type Pokémon have, on average, more HP stats than Grass-type.")
else:
    print("Conclusion: Fail to reject H0. There is insufficient evidence to conclude that Dragon-type Pokémon have higher average HP than Grass-type.")

Conclusion: Reject H0. There is statistically significant evidence that Dragon-type Pokémon have, on average, more HP stats than Grass-type.

In [17]:
df["Legendary"].value_counts()

Legendary
False    735
True      65
Name: count, dtype: int64

In [ ]:
# Ho = stats Legendary (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) = stats Non-Legendary (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed)
# H1 = stats Legendary (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) ≠ stats Non-Legendary (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed)

In [18]:
stats_to_test = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']

In [19]:
legendary_df = df[df['Legendary'] == True]
non_legendary_df = df[df['Legendary'] == False]

In [20]:
alpha = 0.05

In [38]:
for stat in stats_to_test:
    leg_stats = legendary_df[stat]
    non_leg_stats = non_legendary_df[stat]

    _, p_value = st.ttest_ind(leg_stats, non_leg_stats, alternative='two-sided')

    print(p_value)


    if p_value < alpha:
        print(f"Conclusion: Reject H0. There is a statistically significant difference in {stat} between Legendary and Non-Legendary Pokémon.\n")
    else:
        print(f"Conclusion: Fail to reject H0. No significant difference found in {stat}.\n")

3.3306476848461913e-15
Conclusion: Reject H0. There is a statistically significant difference in HP between Legendary and Non-Legendary Pokémon.

7.827253003205333e-24
Conclusion: Reject H0. There is a statistically significant difference in Attack between Legendary and Non-Legendary Pokémon.

1.5842226094427255e-12
Conclusion: Reject H0. There is a statistically significant difference in Defense between Legendary and Non-Legendary Pokémon.

6.314915770427265e-41
Conclusion: Reject H0. There is a statistically significant difference in Sp. Atk between Legendary and Non-Legendary Pokémon.

1.8439809580409597e-26
Conclusion: Reject H0. There is a statistically significant difference in Sp. Def between Legendary and Non-Legendary Pokémon.

2.3540754436898437e-21
Conclusion: Reject H0. There is a statistically significant difference in Speed between Legendary and Non-Legendary Pokémon.

In [40]:
df_2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")

df_2.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [45]:
def calculate_distances(df_2):
  # Define coordinates for school and hospital
  school_coords = (-118, 34)
  hospital_coords = (-122, 37)

  # Calculate Euclidean distance to the school
  df_2["dist_to_school"] = np.sqrt(
      (df_2["longitude"] - school_coords[0]) ** 2
      + (df_2["latitude"] - school_coords[1]) ** 2
  )

  # Calculate Euclidean distance to the hospital
  df_2["dist_to_hospital"] = np.sqrt(
      (df_2["longitude"] - hospital_coords[0]) ** 2
      + (df_2["latitude"] - hospital_coords[1]) ** 2
  )

  return df_2

In [46]:
df_2 = calculate_distances(df_2)

# Define a threshold for being "close" (distance < 0.50)
threshold = 0.50

# Divide the dataset into houses close to either a school or a hospital, and those far away
houses_close = df_2[
    (df_2["dist_to_school"] < threshold) | (df_2["dist_to_hospital"] < threshold)
]
houses_far = df_2[
    (df_2["dist_to_school"] >= threshold)
    & (df_2["dist_to_hospital"] >= threshold)
]

In [ ]:
# H0 : mu_close <= mu_far (Close houses are not more expensive)
# H1:  mu_close > mu_far (Close houses are more expensive)

In [50]:
# Extract the median house value for each group
close_values = houses_close['median_house_value'].dropna()
far_values = houses_far['median_house_value'].dropna()

In [56]:
# Perform One-tailed Independent Two-Sample T-Test (alternative='greater')
_, p_value = st.ttest_ind(close_values, far_values, alternative='greater')

print(p_value)

2.408917945663922e-304

In [58]:
alpha = 0.05
if p_value < alpha:
  print(
      "Conclusion: Reject H0. There is statistically significant evidence that"
      " houses close to a school or hospital are more expensive."
  )
else:
  print(
      "Conclusion: Fail to reject H0. There is insufficient evidence to"
      " conclude that houses close to a school or hospital are more expensive."
  )

Conclusion: Reject H0. There is statistically significant evidence that houses close to a school or hospital are more expensive.