In [1]:
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [3]:
### h0: mean hp of dragon == mean hp of grass 
### h1: mean hp of dragon != mean hp of grass

In [4]:
from scipy.stats import ttest_ind

In [5]:
hp_dragon = df[df['Type 1'] == 'Dragon']['HP']
hp_grass = df[df['Type 1'] == 'Grass']['HP']

t_stat, p_val = ttest_ind(hp_dragon, hp_grass, equal_var=False, alternative='greater')

print("t-statistic:", t_stat)
print("p-value:", p_val)

t-statistic: 3.3349632905124063
p-value: 0.0007993609745420599

In [6]:
### reject the null hypothesis, there is statistical evidence to support that dragon type has higher HP

In [7]:
### h0: mean stats of legendary == stats of non-legendary 
### h1: mean stats of legendary != stats of non-legendary

In [11]:
stats_columns = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']

legendary = df[df['Legendary'] == True]
non_legendary = df[df['Legendary'] == False]

results = {}
for col in stats_columns:
    t_stat, p_val = ttest_ind(legendary[col], non_legendary[col], equal_var=False)
    results[col] = {'t-statistic': t_stat, 'p-value': p_val}

pd.DataFrame(results)

,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
t-statistic,8.981370e+00,1.043813e+01,7.637078e+00,1.341745e+01,1.001570e+01,1.147504e+01
p-value,1.002691e-13,2.520372e-16,4.826998e-11,1.551461e-21,2.294933e-15,1.049016e-18

In [14]:
### reject the null hypothesis, there is statistical evidence to support that legendary pokemon
### have higher stats in all categories than non-legendary pokemon

In [15]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [16]:
### h0: the mean median_house_value close to school/hospital is == the mean median_house_value far to school/hospital 
### h1: he mean median_house_value close to school/hospital is != the mean median_house_value far to school/hospital

In [17]:
import numpy as np

### coords
school = (-118, 34)
hospital = (-122, 37)

### function for euclidean distance
def euclidean_distance(lon, lat, point):
    return np.sqrt((lon - point[0])**2 + (lat - point[1])**2)

### distances to school and hospital
df['dist_school'] = euclidean_distance(df['longitude'], df['latitude'], school)
df['dist_hospital'] = euclidean_distance(df['longitude'], df['latitude'], hospital)

### finding out if house is "close" (<0.50)
df['close_to_facility'] = ((df['dist_school'] < 0.50) | (df['dist_hospital'] < 0.50))

In [18]:
### split df to close and far
close_houses = df[df['close_to_facility'] == True]['median_house_value']
far_houses = df[df['close_to_facility'] == False]['median_house_value']

In [19]:
t_stat, p_val = ttest_ind(close_houses, far_houses, equal_var=False, alternative='greater')

print("t-statistic:", t_stat)
print("p-value:", p_val)

t-statistic: 37.992330214201516
p-value: 1.5032478884296307e-301

In [20]:
### reject the null hypothesis, there is really strong statistical evidence to support that houses close to a school or hospital are 
### much more expensive than houses farther away